# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addClientCase.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addClientCase(object):
    def setupUi(self, addClientCase):
        addClientCase.setObjectName("addClientCase")
        addClientCase.resize(340, 330)
        addClientCase.setStyleSheet("QDialog{\n"
"background-color: white;\n"
"}\n"
"\n"
"#titleWidget{\n"
"background-color: #1d3453;\n"
"}\n"
"#title_2{\n"
"color: white;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border:1px solid gray;\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"QComboBox{\n"
"border: 1px solid black;\n"
"border-radius: 8px;\n"
"background-color: #1d3453;\n"
"color: white;\n"
"height: 35px;\n"
"\n"
"\n"
"}\n"
"\n"
"QDateEdit{\n"
"    border:1px solid gray;\n"
"    border-radius: 8px;\n"
"    padding-left: 15px;\n"
"    height: 35px;\n"
"    background-color: #1d3453;\n"
"color: white;\n"
"}")
        self.titleWidget = QtWidgets.QWidget(addClientCase)
        self.titleWidget.setGeometry(QtCore.QRect(0, 0, 461, 61))
        self.titleWidget.setObjectName("titleWidget")
        self.title_2 = QtWidgets.QLabel(self.titleWidget)
        self.title_2.setGeometry(QtCore.QRect(0, 10, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title_2.setFont(font)
        self.title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_2.setObjectName("title_2")
        self.add_client_Case = QtWidgets.QPushButton(addClientCase)
        self.add_client_Case.setGeometry(QtCore.QRect(30, 260, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.add_client_Case.setFont(font)
        self.add_client_Case.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 139, 0);\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        self.add_client_Case.setObjectName("add_client_Case")
        self.add_info_cancel = QtWidgets.QPushButton(addClientCase)
        self.add_info_cancel.setGeometry(QtCore.QRect(190, 260, 121, 40))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.add_info_cancel.setFont(font)
        self.add_info_cancel.setStyleSheet("QPushButton{\n"
"    background-color: #1d3453;\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(53, 96, 153)\n"
"}")
        self.add_info_cancel.setObjectName("add_info_cancel")
        self.widget = QtWidgets.QWidget(addClientCase)
        self.widget.setGeometry(QtCore.QRect(30, 70, 281, 73))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.client_name_combo = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.client_name_combo.setFont(font)
        self.client_name_combo.setObjectName("client_name_combo")
        self.verticalLayout.addWidget(self.client_name_combo)
        self.widget1 = QtWidgets.QWidget(addClientCase)
        self.widget1.setGeometry(QtCore.QRect(30, 160, 281, 73))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.client_case_combo = QtWidgets.QComboBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.client_case_combo.setFont(font)
        self.client_case_combo.setObjectName("client_case_combo")
        self.verticalLayout_2.addWidget(self.client_case_combo)

        self.retranslateUi(addClientCase)
        QtCore.QMetaObject.connectSlotsByName(addClientCase)

    def retranslateUi(self, addClientCase):
        _translate = QtCore.QCoreApplication.translate
        addClientCase.setWindowTitle(_translate("addClientCase", "Dialog"))
        self.title_2.setText(_translate("addClientCase", "Add New Client Case"))
        self.add_client_Case.setText(_translate("addClientCase", "Add Information"))
        self.add_info_cancel.setText(_translate("addClientCase", "Cancel"))
        self.label_6.setText(_translate("addClientCase", "Client Name"))
        self.label_5.setText(_translate("addClientCase", "Case Name"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addClientCase = QtWidgets.QDialog()
    ui = Ui_addClientCase()
    ui.setupUi(addClientCase)
    addClientCase.show()
    sys.exit(app.exec_())
