# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addClient.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addClient(object):
    def setupUi(self, addClient):
        addClient.setObjectName("addClient")
        addClient.resize(460, 470)
        addClient.setStyleSheet("QDialog{\n"
"background-color: white;\n"
"}\n"
"\n"
"#titleWidget{\n"
"background-color: #1d3453;\n"
"}\n"
"#title {\n"
"color: white;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border:1px solid gray;\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"QComboBox{\n"
"border: 1px solid black;\n"
"border-radius: 8px;\n"
"background-color: #1d3453;\n"
"color: white;\n"
"height: 35px;\n"
"\n"
"\n"
"}")
        self.titleWidget = QtWidgets.QWidget(addClient)
        self.titleWidget.setGeometry(QtCore.QRect(0, 0, 461, 61))
        self.titleWidget.setObjectName("titleWidget")
        self.title = QtWidgets.QLabel(self.titleWidget)
        self.title.setGeometry(QtCore.QRect(60, 10, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.layoutWidget = QtWidgets.QWidget(addClient)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 70, 440, 321))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.clientIDinput = QtWidgets.QLineEdit(self.layoutWidget)
        self.clientIDinput.setMinimumSize(QtCore.QSize(0, 35))
        self.clientIDinput.setMaximumSize(QtCore.QSize(16777215, 35))
        self.clientIDinput.setObjectName("clientIDinput")
        self.verticalLayout.addWidget(self.clientIDinput)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.clientNameinput = QtWidgets.QLineEdit(self.layoutWidget)
        self.clientNameinput.setMinimumSize(QtCore.QSize(0, 35))
        self.clientNameinput.setMaximumSize(QtCore.QSize(16777215, 35))
        self.clientNameinput.setObjectName("clientNameinput")
        self.verticalLayout_2.addWidget(self.clientNameinput)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.clientTypeCombo = QtWidgets.QComboBox(self.layoutWidget)
        self.clientTypeCombo.setMinimumSize(QtCore.QSize(0, 35))
        self.clientTypeCombo.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.clientTypeCombo.setFont(font)
        self.clientTypeCombo.setObjectName("clientTypeCombo")
        self.clientTypeCombo.addItem("")
        self.clientTypeCombo.addItem("")
        self.clientTypeCombo.addItem("")
        self.verticalLayout_4.addWidget(self.clientTypeCombo)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.assignedLawyerCombo = QtWidgets.QComboBox(self.layoutWidget)
        self.assignedLawyerCombo.setMinimumSize(QtCore.QSize(0, 35))
        self.assignedLawyerCombo.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.assignedLawyerCombo.setFont(font)
        self.assignedLawyerCombo.setObjectName("assignedLawyerCombo")
        self.verticalLayout_6.addWidget(self.assignedLawyerCombo)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.clientEmailLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.clientEmailLabel.setFont(font)
        self.clientEmailLabel.setObjectName("clientEmailLabel")
        self.verticalLayout_3.addWidget(self.clientEmailLabel)
        self.clientEmail = QtWidgets.QLineEdit(self.layoutWidget)
        self.clientEmail.setMinimumSize(QtCore.QSize(0, 35))
        self.clientEmail.setMaximumSize(QtCore.QSize(16777215, 35))
        self.clientEmail.setObjectName("clientEmail")
        self.verticalLayout_3.addWidget(self.clientEmail)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.add_client_info = QtWidgets.QPushButton(addClient)
        self.add_client_info.setGeometry(QtCore.QRect(80, 410, 110, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.add_client_info.setFont(font)
        self.add_client_info.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 139, 0);\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        self.add_client_info.setObjectName("add_client_info")
        self.add_lawyer_cancel_2 = QtWidgets.QPushButton(addClient)
        self.add_lawyer_cancel_2.setGeometry(QtCore.QRect(250, 410, 110, 40))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.add_lawyer_cancel_2.setFont(font)
        self.add_lawyer_cancel_2.setStyleSheet("QPushButton{\n"
"    background-color: #1d3453;\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(53, 96, 153)\n"
"}")
        self.add_lawyer_cancel_2.setObjectName("add_lawyer_cancel_2")

        self.retranslateUi(addClient)
        QtCore.QMetaObject.connectSlotsByName(addClient)

    def retranslateUi(self, addClient):
        _translate = QtCore.QCoreApplication.translate
        addClient.setWindowTitle(_translate("addClient", "Dialog"))
        self.title.setText(_translate("addClient", "Add New Client"))
        self.label_2.setText(_translate("addClient", "Client ID"))
        self.label_3.setText(_translate("addClient", "Client Name"))
        self.label_5.setText(_translate("addClient", "Select Type"))
        self.clientTypeCombo.setItemText(0, _translate("addClient", "Individual"))
        self.clientTypeCombo.setItemText(1, _translate("addClient", "Business Owner"))
        self.clientTypeCombo.setItemText(2, _translate("addClient", "Company"))
        self.label_7.setText(_translate("addClient", "Assigned Lawyer"))
        self.clientEmailLabel.setText(_translate("addClient", "E-Mail"))
        self.add_client_info.setText(_translate("addClient", "Add Client"))
        self.add_lawyer_cancel_2.setText(_translate("addClient", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addClient = QtWidgets.QDialog()
    ui = Ui_addClient()
    ui.setupUi(addClient)
    addClient.show()
    sys.exit(app.exec_())
