# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addCase.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addCase(object):
    def setupUi(self, addCase):
        addCase.setObjectName("addCase")
        addCase.resize(460, 470)
        addCase.setStyleSheet("QDialog{\n"
"background-color: white;\n"
"}\n"
"\n"
"#titleWidget{\n"
"background-color: #1d3453;\n"
"}\n"
"#title {\n"
"color: white;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border:1px solid gray;\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"QComboBox{\n"
"border: 1px solid black;\n"
"border-radius: 8px;\n"
"background-color: #1d3453;\n"
"color: white;\n"
"height: 35px;\n"
"\n"
"\n"
"}\n"
"\n"
"QDateEdit{\n"
"    border:1px solid gray;\n"
"    border-radius: 8px;\n"
"    padding-left: 15px;\n"
"    height: 35px;\n"
"    background-color: #1d3453;\n"
"color: white;\n"
"}")
        self.add_case_cancel = QtWidgets.QPushButton(addCase)
        self.add_case_cancel.setGeometry(QtCore.QRect(270, 410, 110, 40))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.add_case_cancel.setFont(font)
        self.add_case_cancel.setStyleSheet("QPushButton{\n"
"    background-color: #1d3453;\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(53, 96, 153)\n"
"}")
        self.add_case_cancel.setObjectName("add_case_cancel")
        self.titleWidget = QtWidgets.QWidget(addCase)
        self.titleWidget.setGeometry(QtCore.QRect(0, 0, 461, 61))
        self.titleWidget.setObjectName("titleWidget")
        self.title = QtWidgets.QLabel(self.titleWidget)
        self.title.setGeometry(QtCore.QRect(60, 10, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.add_case_info = QtWidgets.QPushButton(addCase)
        self.add_case_info.setGeometry(QtCore.QRect(70, 410, 110, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.add_case_info.setFont(font)
        self.add_case_info.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 139, 0);\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        self.add_case_info.setObjectName("add_case_info")
        self.layoutWidget = QtWidgets.QWidget(addCase)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 70, 440, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.caseIDinput = QtWidgets.QLineEdit(self.layoutWidget)
        self.caseIDinput.setMinimumSize(QtCore.QSize(0, 35))
        self.caseIDinput.setMaximumSize(QtCore.QSize(16777215, 35))
        self.caseIDinput.setObjectName("caseIDinput")
        self.verticalLayout.addWidget(self.caseIDinput)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.caseNameinput = QtWidgets.QLineEdit(self.layoutWidget)
        self.caseNameinput.setMinimumSize(QtCore.QSize(0, 35))
        self.caseNameinput.setMaximumSize(QtCore.QSize(16777215, 35))
        self.caseNameinput.setObjectName("caseNameinput")
        self.verticalLayout_2.addWidget(self.caseNameinput)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.caseType = QtWidgets.QComboBox(self.layoutWidget)
        self.caseType.setMinimumSize(QtCore.QSize(0, 35))
        self.caseType.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.caseType.setFont(font)
        self.caseType.setObjectName("caseType")
        self.caseType.addItem("")
        self.caseType.addItem("")
        self.caseType.addItem("")
        self.caseType.addItem("")
        self.caseType.addItem("")
        self.verticalLayout_4.addWidget(self.caseType)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.startDate = QtWidgets.QDateEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.startDate.setFont(font)
        self.startDate.setObjectName("startDate")
        self.verticalLayout_5.addWidget(self.startDate)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.endDate = QtWidgets.QLineEdit(self.layoutWidget)
        self.endDate.setMinimumSize(QtCore.QSize(150, 35))
        self.endDate.setMaximumSize(QtCore.QSize(135, 16777215))
        self.endDate.setStyleSheet("#endDate{\n"
"    width: 50px;\n"
"}")
        self.endDate.setText("")
        self.endDate.setObjectName("endDate")
        self.verticalLayout_6.addWidget(self.endDate, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.caseStatus = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.caseStatus.setFont(font)
        self.caseStatus.setObjectName("caseStatus")
        self.caseStatus.addItem("")
        self.caseStatus.addItem("")
        self.caseStatus.addItem("")
        self.caseStatus.addItem("")
        self.verticalLayout_3.addWidget(self.caseStatus)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)

        self.retranslateUi(addCase)
        QtCore.QMetaObject.connectSlotsByName(addCase)

    def retranslateUi(self, addCase):
        _translate = QtCore.QCoreApplication.translate
        addCase.setWindowTitle(_translate("addCase", "Dialog"))
        self.add_case_cancel.setText(_translate("addCase", "Cancel"))
        self.title.setText(_translate("addCase", "Add New Case"))
        self.add_case_info.setText(_translate("addCase", " Add Case"))
        self.label_2.setText(_translate("addCase", "Case ID"))
        self.label_3.setText(_translate("addCase", "Case Name"))
        self.label_5.setText(_translate("addCase", "Case Type"))
        self.caseType.setItemText(0, _translate("addCase", "Civil"))
        self.caseType.setItemText(1, _translate("addCase", "Criminal"))
        self.caseType.setItemText(2, _translate("addCase", "Appeal"))
        self.caseType.setItemText(3, _translate("addCase", "Class Action"))
        self.caseType.setItemText(4, _translate("addCase", "Bankruptcy"))
        self.label_6.setText(_translate("addCase", "Start Date"))
        self.label_7.setText(_translate("addCase", "End Date"))
        self.label_4.setText(_translate("addCase", "Status"))
        self.caseStatus.setItemText(0, _translate("addCase", "Pending"))
        self.caseStatus.setItemText(1, _translate("addCase", "Ongoing"))
        self.caseStatus.setItemText(2, _translate("addCase", "Closed"))
        self.caseStatus.setItemText(3, _translate("addCase", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addCase = QtWidgets.QDialog()
    ui = Ui_addCase()
    ui.setupUi(addCase)
    addCase.show()
    sys.exit(app.exec_())
