# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editClient.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editClient(object):
    def setupUi(self, editClient):
        editClient.setObjectName("editClient")
        editClient.resize(460, 471)
        editClient.setStyleSheet("QDialog{\n"
"background-color: white;\n"
"}\n"
"\n"
"#titleWidget{\n"
"background-color: #1d3453;\n"
"}\n"
"#title {\n"
"color: white;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border:1px solid gray;\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"QComboBox{\n"
"border: 1px solid black;\n"
"border-radius: 8px;\n"
"background-color: #1d3453;\n"
"color: white;\n"
"height: 35px;\n"
"\n"
"\n"
"}")
        self.edit_lawyer_cancel = QtWidgets.QPushButton(editClient)
        self.edit_lawyer_cancel.setGeometry(QtCore.QRect(250, 410, 110, 40))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.edit_lawyer_cancel.setFont(font)
        self.edit_lawyer_cancel.setStyleSheet("QPushButton{\n"
"    background-color: #1d3453;\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(53, 96, 153)\n"
"}")
        self.edit_lawyer_cancel.setObjectName("edit_lawyer_cancel")
        self.edit_client_info = QtWidgets.QPushButton(editClient)
        self.edit_client_info.setGeometry(QtCore.QRect(80, 410, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.edit_client_info.setFont(font)
        self.edit_client_info.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 139, 0);\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        self.edit_client_info.setObjectName("edit_client_info")
        self.titleWidget = QtWidgets.QWidget(editClient)
        self.titleWidget.setGeometry(QtCore.QRect(0, 0, 461, 61))
        self.titleWidget.setObjectName("titleWidget")
        self.title = QtWidgets.QLabel(self.titleWidget)
        self.title.setGeometry(QtCore.QRect(50, 10, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.layoutWidget = QtWidgets.QWidget(editClient)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 70, 440, 321))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.clientIDinput_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.clientIDinput_edit.setMinimumSize(QtCore.QSize(0, 35))
        self.clientIDinput_edit.setMaximumSize(QtCore.QSize(16777215, 35))
        self.clientIDinput_edit.setObjectName("clientIDinput_edit")
        self.verticalLayout.addWidget(self.clientIDinput_edit)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.clientNameinput_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.clientNameinput_edit.setMinimumSize(QtCore.QSize(0, 35))
        self.clientNameinput_edit.setMaximumSize(QtCore.QSize(16777215, 35))
        self.clientNameinput_edit.setObjectName("clientNameinput_edit")
        self.verticalLayout_2.addWidget(self.clientNameinput_edit)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.clientTypeCombo_edit = QtWidgets.QComboBox(self.layoutWidget)
        self.clientTypeCombo_edit.setMinimumSize(QtCore.QSize(0, 35))
        self.clientTypeCombo_edit.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.clientTypeCombo_edit.setFont(font)
        self.clientTypeCombo_edit.setObjectName("clientTypeCombo_edit")
        self.clientTypeCombo_edit.addItem("")
        self.clientTypeCombo_edit.addItem("")
        self.clientTypeCombo_edit.addItem("")
        self.verticalLayout_4.addWidget(self.clientTypeCombo_edit)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.assignedLawyerCombo_edit = QtWidgets.QComboBox(self.layoutWidget)
        self.assignedLawyerCombo_edit.setMinimumSize(QtCore.QSize(0, 35))
        self.assignedLawyerCombo_edit.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.assignedLawyerCombo_edit.setFont(font)
        self.assignedLawyerCombo_edit.setObjectName("assignedLawyerCombo_edit")
        self.verticalLayout_6.addWidget(self.assignedLawyerCombo_edit)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.clientEmailLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.clientEmailLabel.setFont(font)
        self.clientEmailLabel.setObjectName("clientEmailLabel")
        self.verticalLayout_3.addWidget(self.clientEmailLabel)
        self.clientEmail_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.clientEmail_edit.setMinimumSize(QtCore.QSize(0, 35))
        self.clientEmail_edit.setMaximumSize(QtCore.QSize(16777215, 35))
        self.clientEmail_edit.setObjectName("clientEmail_edit")
        self.verticalLayout_3.addWidget(self.clientEmail_edit)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)

        self.retranslateUi(editClient)
        QtCore.QMetaObject.connectSlotsByName(editClient)

    def retranslateUi(self, editClient):
        _translate = QtCore.QCoreApplication.translate
        editClient.setWindowTitle(_translate("editClient", "Dialog"))
        self.edit_lawyer_cancel.setText(_translate("editClient", "Cancel"))
        self.edit_client_info.setText(_translate("editClient", "Edit Client Info"))
        self.title.setText(_translate("editClient", "Edit Client Information"))
        self.label_2.setText(_translate("editClient", "Client ID"))
        self.label_3.setText(_translate("editClient", "Client Name"))
        self.label_5.setText(_translate("editClient", "Select Type"))
        self.clientTypeCombo_edit.setItemText(0, _translate("editClient", "Individual"))
        self.clientTypeCombo_edit.setItemText(1, _translate("editClient", "Business Owner"))
        self.clientTypeCombo_edit.setItemText(2, _translate("editClient", "Company"))
        self.label_7.setText(_translate("editClient", "Assigned Lawyer"))
        self.clientEmailLabel.setText(_translate("editClient", "E-Mail"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editClient = QtWidgets.QDialog()
    ui = Ui_editClient()
    ui.setupUi(editClient)
    editClient.show()
    sys.exit(app.exec_())
