# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editCase.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(460, 470)
        Dialog.setStyleSheet("QDialog{\n"
"background-color: white;\n"
"}\n"
"\n"
"#titleWidget{\n"
"background-color: #1d3453;\n"
"}\n"
"#title {\n"
"color: white;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border:1px solid gray;\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"QComboBox{\n"
"border: 1px solid black;\n"
"border-radius: 8px;\n"
"background-color: #1d3453;\n"
"color: white;\n"
"height: 35px;\n"
"\n"
"\n"
"}\n"
"\n"
"QDateEdit{\n"
"    border:1px solid gray;\n"
"    border-radius: 8px;\n"
"    padding-left: 15px;\n"
"    height: 35px;\n"
"    background-color: #1d3453;\n"
"color: white;\n"
"}")
        self.edit_case_info = QtWidgets.QPushButton(Dialog)
        self.edit_case_info.setGeometry(QtCore.QRect(70, 410, 110, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.edit_case_info.setFont(font)
        self.edit_case_info.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 139, 0);\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        self.edit_case_info.setObjectName("edit_case_info")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 70, 440, 330))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.caseIDinput_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.caseIDinput_edit.setMinimumSize(QtCore.QSize(0, 35))
        self.caseIDinput_edit.setMaximumSize(QtCore.QSize(16777215, 35))
        self.caseIDinput_edit.setObjectName("caseIDinput_edit")
        self.verticalLayout.addWidget(self.caseIDinput_edit)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.caseNameinput_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.caseNameinput_edit.setMinimumSize(QtCore.QSize(0, 35))
        self.caseNameinput_edit.setMaximumSize(QtCore.QSize(16777215, 35))
        self.caseNameinput_edit.setObjectName("caseNameinput_edit")
        self.verticalLayout_2.addWidget(self.caseNameinput_edit)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.caseType_edit = QtWidgets.QComboBox(self.layoutWidget)
        self.caseType_edit.setMinimumSize(QtCore.QSize(0, 35))
        self.caseType_edit.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.caseType_edit.setFont(font)
        self.caseType_edit.setObjectName("caseType_edit")
        self.caseType_edit.addItem("")
        self.caseType_edit.addItem("")
        self.caseType_edit.addItem("")
        self.caseType_edit.addItem("")
        self.caseType_edit.addItem("")
        self.verticalLayout_4.addWidget(self.caseType_edit)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.startDate_edit = QtWidgets.QDateEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.startDate_edit.setFont(font)
        self.startDate_edit.setObjectName("startDate_edit")
        self.verticalLayout_5.addWidget(self.startDate_edit)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.endDate_edit = QtWidgets.QDateEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.endDate_edit.setFont(font)
        self.endDate_edit.setObjectName("endDate_edit")
        self.verticalLayout_6.addWidget(self.endDate_edit)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.caseStatus_edit = QtWidgets.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.caseStatus_edit.setFont(font)
        self.caseStatus_edit.setObjectName("caseStatus_edit")
        self.caseStatus_edit.addItem("")
        self.caseStatus_edit.addItem("")
        self.caseStatus_edit.addItem("")
        self.caseStatus_edit.addItem("")
        self.verticalLayout_3.addWidget(self.caseStatus_edit)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.titleWidget = QtWidgets.QWidget(Dialog)
        self.titleWidget.setGeometry(QtCore.QRect(0, 0, 461, 61))
        self.titleWidget.setObjectName("titleWidget")
        self.title = QtWidgets.QLabel(self.titleWidget)
        self.title.setGeometry(QtCore.QRect(60, 10, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.edit_case_cancel = QtWidgets.QPushButton(Dialog)
        self.edit_case_cancel.setGeometry(QtCore.QRect(270, 410, 110, 40))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.edit_case_cancel.setFont(font)
        self.edit_case_cancel.setStyleSheet("QPushButton{\n"
"    background-color: #1d3453;\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(53, 96, 153)\n"
"}")
        self.edit_case_cancel.setObjectName("edit_case_cancel")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.edit_case_info.setText(_translate("Dialog", "Edit Case"))
        self.label_2.setText(_translate("Dialog", "Case ID"))
        self.label_3.setText(_translate("Dialog", "Case Name"))
        self.label_5.setText(_translate("Dialog", "Case Type"))
        self.caseType_edit.setItemText(0, _translate("Dialog", "Civil"))
        self.caseType_edit.setItemText(1, _translate("Dialog", "Criminal"))
        self.caseType_edit.setItemText(2, _translate("Dialog", "Appeal"))
        self.caseType_edit.setItemText(3, _translate("Dialog", "Class Action"))
        self.caseType_edit.setItemText(4, _translate("Dialog", "Bankruptcy"))
        self.label_6.setText(_translate("Dialog", "Start Date"))
        self.label_7.setText(_translate("Dialog", "End Date"))
        self.label_4.setText(_translate("Dialog", "Status"))
        self.caseStatus_edit.setItemText(0, _translate("Dialog", "Pending"))
        self.caseStatus_edit.setItemText(1, _translate("Dialog", "Ongoing"))
        self.caseStatus_edit.setItemText(2, _translate("Dialog", "Closed"))
        self.caseStatus_edit.setItemText(3, _translate("Dialog", "Open"))
        self.title.setText(_translate("Dialog", "Edit Case Information"))
        self.edit_case_cancel.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
