# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editLawyer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_editLawyer(object):
    def setupUi(self, editLawyer):
        editLawyer.setObjectName("editLawyer")
        editLawyer.resize(460, 470)
        editLawyer.setStyleSheet("QDialog{\n"
"background-color: white;\n"
"}\n"
"\n"
"#titleWidget{\n"
"background-color: #1d3453;\n"
"}\n"
"#title {\n"
"color: white;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border:1px solid gray;\n"
"    border-radius: 6px;\n"
"    padding-left: 15px;\n"
"    height: 35px;\n"
"}\n"
"\n"
"QComboBox{\n"
"border: 1px solid black;\n"
"border-radius: 8px;\n"
"background-color: #1d3453;\n"
"color: white;\n"
"height: 35px;\n"
"\n"
"\n"
"}\n"
"\n"
"")
        self.edit_lawyer_info = QtWidgets.QPushButton(editLawyer)
        self.edit_lawyer_info.setGeometry(QtCore.QRect(70, 410, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.edit_lawyer_info.setFont(font)
        self.edit_lawyer_info.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 139, 0);\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        self.edit_lawyer_info.setObjectName("edit_lawyer_info")
        self.layoutWidget = QtWidgets.QWidget(editLawyer)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 70, 440, 321))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.edit_LawyerID = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_LawyerID.setMinimumSize(QtCore.QSize(0, 35))
        self.edit_LawyerID.setMaximumSize(QtCore.QSize(16777215, 35))
        self.edit_LawyerID.setObjectName("edit_LawyerID")
        self.verticalLayout.addWidget(self.edit_LawyerID)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.edit_LawyerName = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_LawyerName.setMinimumSize(QtCore.QSize(0, 35))
        self.edit_LawyerName.setMaximumSize(QtCore.QSize(16777215, 35))
        self.edit_LawyerName.setObjectName("edit_LawyerName")
        self.verticalLayout_2.addWidget(self.edit_LawyerName)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.edit_LawyerGender = QtWidgets.QComboBox(self.layoutWidget)
        self.edit_LawyerGender.setMinimumSize(QtCore.QSize(0, 35))
        self.edit_LawyerGender.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.edit_LawyerGender.setFont(font)
        self.edit_LawyerGender.setObjectName("edit_LawyerGender")
        self.edit_LawyerGender.addItem("")
        self.edit_LawyerGender.addItem("")
        self.edit_LawyerGender.addItem("")
        self.edit_LawyerGender.addItem("")
        self.verticalLayout_4.addWidget(self.edit_LawyerGender)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.edit_Position = QtWidgets.QComboBox(self.layoutWidget)
        self.edit_Position.setMinimumSize(QtCore.QSize(0, 35))
        self.edit_Position.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.edit_Position.setFont(font)
        self.edit_Position.setObjectName("edit_Position")
        self.edit_Position.addItem("")
        self.edit_Position.addItem("")
        self.edit_Position.addItem("")
        self.edit_Position.addItem("")
        self.edit_Position.addItem("")
        self.verticalLayout_5.addWidget(self.edit_Position)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.edit_Specialization = QtWidgets.QComboBox(self.layoutWidget)
        self.edit_Specialization.setMinimumSize(QtCore.QSize(0, 35))
        self.edit_Specialization.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.edit_Specialization.setFont(font)
        self.edit_Specialization.setObjectName("edit_Specialization")
        self.edit_Specialization.addItem("")
        self.edit_Specialization.addItem("")
        self.edit_Specialization.addItem("")
        self.edit_Specialization.addItem("")
        self.edit_Specialization.addItem("")
        self.edit_Specialization.addItem("")
        self.verticalLayout_6.addWidget(self.edit_Specialization)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.edit_LawyerEmail = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_LawyerEmail.setMinimumSize(QtCore.QSize(0, 35))
        self.edit_LawyerEmail.setMaximumSize(QtCore.QSize(16777215, 35))
        self.edit_LawyerEmail.setObjectName("edit_LawyerEmail")
        self.verticalLayout_3.addWidget(self.edit_LawyerEmail)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.titleWidget = QtWidgets.QWidget(editLawyer)
        self.titleWidget.setGeometry(QtCore.QRect(0, 0, 461, 61))
        self.titleWidget.setObjectName("titleWidget")
        self.title = QtWidgets.QLabel(self.titleWidget)
        self.title.setGeometry(QtCore.QRect(60, 10, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.edit_cancel_btn = QtWidgets.QPushButton(editLawyer)
        self.edit_cancel_btn.setGeometry(QtCore.QRect(270, 410, 110, 40))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.edit_cancel_btn.setFont(font)
        self.edit_cancel_btn.setStyleSheet("QPushButton{\n"
"    background-color: #1d3453;\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(53, 96, 153)\n"
"}")
        self.edit_cancel_btn.setObjectName("edit_cancel_btn")

        self.retranslateUi(editLawyer)
        QtCore.QMetaObject.connectSlotsByName(editLawyer)

    def retranslateUi(self, editLawyer):
        _translate = QtCore.QCoreApplication.translate
        editLawyer.setWindowTitle(_translate("editLawyer", "Dialog"))
        self.edit_lawyer_info.setText(_translate("editLawyer", "Edit Lawyer Info"))
        self.label_2.setText(_translate("editLawyer", "Lawyer ID"))
        self.label_3.setText(_translate("editLawyer", "Name"))
        self.label_5.setText(_translate("editLawyer", "Select Gender"))
        self.edit_LawyerGender.setItemText(0, _translate("editLawyer", "Male"))
        self.edit_LawyerGender.setItemText(1, _translate("editLawyer", "Female"))
        self.edit_LawyerGender.setItemText(2, _translate("editLawyer", "Nonbinary"))
        self.edit_LawyerGender.setItemText(3, _translate("editLawyer", "Prefer not to say"))
        self.label_6.setText(_translate("editLawyer", "Select Position"))
        self.edit_Position.setItemText(0, _translate("editLawyer", "Junior Associate"))
        self.edit_Position.setItemText(1, _translate("editLawyer", "Senior Associate"))
        self.edit_Position.setItemText(2, _translate("editLawyer", "Junior Partner"))
        self.edit_Position.setItemText(3, _translate("editLawyer", "Senior Partner"))
        self.edit_Position.setItemText(4, _translate("editLawyer", "Managing Partner"))
        self.label_7.setText(_translate("editLawyer", "Lawyer Specialization"))
        self.edit_Specialization.setItemText(0, _translate("editLawyer", "Corporate Law"))
        self.edit_Specialization.setItemText(1, _translate("editLawyer", "Criminal Law"))
        self.edit_Specialization.setItemText(2, _translate("editLawyer", "Finance Law"))
        self.edit_Specialization.setItemText(3, _translate("editLawyer", "Bankruptcy Law"))
        self.edit_Specialization.setItemText(4, _translate("editLawyer", "Intellectual Property Law"))
        self.edit_Specialization.setItemText(5, _translate("editLawyer", "Labor Law"))
        self.label_4.setText(_translate("editLawyer", "E-Mail"))
        self.title.setText(_translate("editLawyer", "Edit Lawyer Information"))
        self.edit_cancel_btn.setText(_translate("editLawyer", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    editLawyer = QtWidgets.QDialog()
    ui = Ui_editLawyer()
    ui.setupUi(editLawyer)
    editLawyer.show()
    sys.exit(app.exec_())
