# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1182, 728)
        Form.setStyleSheet("/*Set style for app title widget */\n"
"#titleWidget{\n"
"    background-color: #1d3656;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-left-radius: 10px;\n"
"    box-shadow:  20px 20px 60px #309980,\n"
"             -20px -20px 60px #42cfae;\n"
"}\n"
"\n"
"#titleWidget QLabel{\n"
"    color: rgba(255,255,255,0.8);\n"
"    \n"
"}\n"
"\n"
"#titleLabel1{\n"
"    font-size: 45px;\n"
"}\n"
"\n"
"#titleLabel2{\n"
"    font-size: 45px;\n"
"}\n"
"\n"
"#titleLabel3{\n"
"    font-size: 45px;\n"
"}\n"
"\n"
"/*Set style for function widget*/\n"
"\n"
"#loginWidget{\n"
"    background-color:     #f6f6f6;\n"
"    border-top-right-radius: 10px;\n"
"    border-bottom-right-radius:10px;\n"
"    \n"
"}\n"
"\n"
"#loginLabel{\n"
"    font-size: 45px;\n"
"}\n"
"\n"
"#noteLabel{\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"#userLabel{\n"
"    font-size:18px;\n"
"}\n"
"\n"
"#passLabel{\n"
"    font-size: 18px;\n"
"}\n"
"\n"
"#exitButton{\n"
"    color:white;\n"
"    background: rgb(217, 0, 0);\n"
"    border-radius: 1em;\n"
"}\n"
"#exitButton:hover{\n"
"    color:white;\n"
"    background: rgb(255, 92, 92);\n"
"    border-radius: 1em;\n"
"}\n"
"\n"
"#loginButton{\n"
" color: white;\n"
"  padding: 0.7em 1.7em;\n"
"  font-size: 18px;\n"
"  border-radius: 0.5em;\n"
"  background: #1d3656;\n"
"  cursor: pointer;\n"
"  border: 1px solid #e8e8e8;\n"
"  transition: all 0.3s;\n"
"  box-shadow: 6px 6px 12px #c5c5c5, -6px -6px 12px #ffffff;\n"
"}\n"
"\n"
"#loginButton:hover {\n"
"  background-color: #3aad00;\n"
"  box-shadow: 0px 15px 20px rgba(46, 229, 157, 0.4);\n"
"  color: #fff;\n"
"  transform: translateY(-7px);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"#titleFrame{\n"
"    border: 5px solid #cba535;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.titleWidget = QtWidgets.QWidget(Form)
        self.titleWidget.setGeometry(QtCore.QRect(90, 70, 500, 591))
        self.titleWidget.setMaximumSize(QtCore.QSize(500, 600))
        self.titleWidget.setObjectName("titleWidget")
        self.titleFrame = QtWidgets.QFrame(self.titleWidget)
        self.titleFrame.setGeometry(QtCore.QRect(40, 120, 421, 331))
        self.titleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.titleFrame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 401, 239))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.titleLabel1.setFont(font)
        self.titleLabel1.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel1.setObjectName("titleLabel1")
        self.verticalLayout.addWidget(self.titleLabel1)
        self.titleLabel2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.titleLabel2.setFont(font)
        self.titleLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel2.setObjectName("titleLabel2")
        self.verticalLayout.addWidget(self.titleLabel2)
        self.titleLabel3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.titleLabel3.setFont(font)
        self.titleLabel3.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel3.setObjectName("titleLabel3")
        self.verticalLayout.addWidget(self.titleLabel3)
        self.loginWidget = QtWidgets.QWidget(Form)
        self.loginWidget.setGeometry(QtCore.QRect(590, 70, 500, 591))
        self.loginWidget.setObjectName("loginWidget")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.loginWidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(70, 80, 294, 117))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.loginLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Poppins Medium")
        font.setPointSize(-1)
        self.loginLabel.setFont(font)
        self.loginLabel.setObjectName("loginLabel")
        self.verticalLayout_4.addWidget(self.loginLabel)
        self.noteLabel = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        self.noteLabel.setFont(font)
        self.noteLabel.setObjectName("noteLabel")
        self.verticalLayout_4.addWidget(self.noteLabel)
        self.exitButton = QtWidgets.QPushButton(self.loginWidget)
        self.exitButton.setGeometry(QtCore.QRect(440, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        self.exitButton.setFont(font)
        self.exitButton.setObjectName("exitButton")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.loginWidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(70, 220, 361, 85))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.userLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        self.userLabel.setFont(font)
        self.userLabel.setStyleSheet("")
        self.userLabel.setObjectName("userLabel")
        self.verticalLayout_2.addWidget(self.userLabel)
        self.userInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.userInput.setStyleSheet("#userInput{\n"
"                    box-sizing: border-box;\n"
"                   \n"
"                    font-size: 16px;\n"
"                    vertical-align: baseline;\n"
"                    font-weight: 400;\n"
"                    line-height: 1.29;\n"
"                    letter-spacing: .16px;\n"
"                    border-radius: 0;\n"
"                    outline: 2px solid transparent;\n"
"                    outline-offset: -2px;\n"
"                    width: 100%;\n"
"                    height: 40px;\n"
"                    border: none;\n"
"                    border-bottom: 1px solid #8d8d8d;\n"
"                    background-color: #f4f4f4;\n"
"                    padding: 0 16px;\n"
"                    color: #161616;\n"
"}\n"
" #userInput:focus{\n"
"                        border: 2px solid black;\n"
"                    }\n"
"                ")
        self.userInput.setObjectName("userInput")
        self.verticalLayout_2.addWidget(self.userInput)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.loginWidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(70, 310, 361, 81))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.passLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        self.passLabel.setFont(font)
        self.passLabel.setObjectName("passLabel")
        self.verticalLayout_3.addWidget(self.passLabel)
        self.passInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.passInput.setStyleSheet("#passInput{\n"
"                    box-sizing: border-box;\n"
"                   \n"
"                    font-size: 16px;\n"
"                    vertical-align: baseline;\n"
"                    font-weight: 400;\n"
"                    line-height: 1.29;\n"
"                    letter-spacing: .16px;\n"
"                    border-radius: 0;\n"
"                    outline: 2px solid transparent;\n"
"                    outline-offset: -2px;\n"
"                    width: 100%;\n"
"                    height: 40px;\n"
"                    border: none;\n"
"                    border-bottom: 1px solid #8d8d8d;\n"
"                    background-color: #f4f4f4;\n"
"                    padding: 0 16px;\n"
"                    color: #161616;\n"
"}\n"
" #passInput:focus{\n"
"                        border: 2px solid black;\n"
"                    }\n"
"                \n"
"\n"
"")
        self.passInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passInput.setClearButtonEnabled(False)
        self.passInput.setObjectName("passInput")
        self.verticalLayout_3.addWidget(self.passInput)
        self.loginButton = QtWidgets.QPushButton(self.loginWidget)
        self.loginButton.setGeometry(QtCore.QRect(130, 430, 231, 63))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.titleLabel1.setText(_translate("Form", " Law Firm"))
        self.titleLabel2.setText(_translate("Form", "Management"))
        self.titleLabel3.setText(_translate("Form", "System"))
        self.loginLabel.setText(_translate("Form", "Login"))
        self.noteLabel.setText(_translate("Form", "Please sign in to continue."))
        self.exitButton.setText(_translate("Form", "Exit"))
        self.userLabel.setText(_translate("Form", "Admin Username:"))
        self.userInput.setPlaceholderText(_translate("Form", "Enter your username."))
        self.passLabel.setText(_translate("Form", "Password:"))
        self.passInput.setPlaceholderText(_translate("Form", "Enter your password."))
        self.loginButton.setText(_translate("Form", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
