# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainsys.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1211, 726)
        MainWindow.setStyleSheet("#sidebar{\n"
"background-color: #1d3453;\n"
"}\n"
"\n"
"#lawyerButton{\n"
"  border: none;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  font-size: 18px;\n"
"  outline: 0;\n"
"  padding: 16px 21px;\n"
"  position: relative;\n"
"text-align: left;\n"
"  text-decoration: none;\n"
"  transition: all .3s;\n"
"}\n"
"\n"
"#lawyerButton:checked {\n"
" background-color: #F5FAFE;\n"
"color: #1d3453;\n"
"}\n"
"\n"
"#clientButton{\n"
"  border: none;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  font-size: 18px;\n"
"  outline: 0;\n"
"  padding: 16px 21px;\n"
"  position: relative;\n"
"text-align: left;\n"
"  text-decoration: none;\n"
"  transition: all .3s;\n"
"}\n"
"\n"
"#clientButton:checked {\n"
" background-color: #F5FAFE;\n"
"color: #1d3453;\n"
"}\n"
"\n"
"#caseButton{\n"
"  border: none;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  font-size: 18px;\n"
"  outline: 0;\n"
"  padding: 16px 21px;\n"
"  position: relative;\n"
"text-align: left;\n"
"  text-decoration: none;\n"
"  transition: all .3s;\n"
"}\n"
"#caseButton:checked {\n"
" background-color: #F5FAFE;\n"
"color: #1d3453;\n"
"}\n"
"\n"
"\n"
"#caseButton_2{\n"
"  border: none;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  font-size: 12px;\n"
"  outline: 0;\n"
"  padding: 6px 8px;\n"
"  position: relative;\n"
"text-align: right;\n"
"  text-decoration: none;\n"
"  transition: all .3s;\n"
"}\n"
"\n"
"#caseButton_2:checked {\n"
" background-color: #F5FAFE;\n"
"color: #1d3453;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"background-color: #142b39; \n"
"color: white; \n"
"font-weight: bold; \n"
"font-family: Poppins;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sidebar = QtWidgets.QWidget(self.centralwidget)
        self.sidebar.setGeometry(QtCore.QRect(0, 60, 201, 671))
        self.sidebar.setStyleSheet("#QPushButton{\n"
"  border: none;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  font-size: 18px;\n"
"  outline: 0;\n"
"  padding: 16px 21px;\n"
"  position: relative;\n"
"text-align: left;\n"
"  text-decoration: none;\n"
"  transition: all .3s;\n"
"}\n"
"#QPushButton:checked {\n"
" background-color: #F5FAFE;\n"
"color: #1d3453;\n"
"}")
        self.sidebar.setObjectName("sidebar")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.sidebar)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 201, 284))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lawyerButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.lawyerButton.setFont(font)
        self.lawyerButton.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/lawyer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icon/lawyerdark.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.lawyerButton.setIcon(icon)
        self.lawyerButton.setCheckable(True)
        self.lawyerButton.setAutoExclusive(True)
        self.lawyerButton.setObjectName("lawyerButton")
        self.verticalLayout.addWidget(self.lawyerButton)
        self.clientButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.clientButton.setFont(font)
        self.clientButton.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/client.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icon/clientdark.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.clientButton.setIcon(icon1)
        self.clientButton.setCheckable(True)
        self.clientButton.setAutoExclusive(True)
        self.clientButton.setObjectName("clientButton")
        self.verticalLayout.addWidget(self.clientButton)
        self.caseButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.caseButton.setFont(font)
        self.caseButton.setStyleSheet("#caseButton{\n"
"  border: none;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  font-size: 18px;\n"
"  outline: 0;\n"
"  padding: 16px 21px;\n"
"  position: relative;\n"
"text-align: left;\n"
"  text-decoration: none;\n"
"  transition: all .3s;\n"
"}\n"
"#caseButton:checked {\n"
" background-color: #F5FAFE;\n"
"color: #1d3453;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/case.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icon/casedark.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.caseButton.setIcon(icon2)
        self.caseButton.setCheckable(True)
        self.caseButton.setAutoExclusive(True)
        self.caseButton.setObjectName("caseButton")
        self.verticalLayout.addWidget(self.caseButton)
        self.caseButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.caseButton_2.setFont(font)
        self.caseButton_2.setStyleSheet("")
        self.caseButton_2.setIcon(icon2)
        self.caseButton_2.setCheckable(True)
        self.caseButton_2.setAutoExclusive(True)
        self.caseButton_2.setObjectName("caseButton_2")
        self.verticalLayout.addWidget(self.caseButton_2)
        self.exitButton = QtWidgets.QPushButton(self.sidebar)
        self.exitButton.setGeometry(QtCore.QRect(0, 600, 201, 53))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.exitButton.setFont(font)
        self.exitButton.setStyleSheet("#exitButton{\n"
"  border: none;\n"
"  color: #fff;\n"
"  cursor: pointer;\n"
"  font-size: 18px;\n"
"  outline: 0;\n"
"  padding: 16px 21px;\n"
"  position: relative;\n"
"text-align: center;\n"
"  text-decoration: none;\n"
"  transition: all .3s;\n"
"}\n"
"\n"
"#exitButton:checked {\n"
" background-color: #F5FAFE;\n"
"color: #1d3453;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/exit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icon/exitdark.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.exitButton.setIcon(icon3)
        self.exitButton.setCheckable(True)
        self.exitButton.setChecked(False)
        self.exitButton.setAutoRepeat(False)
        self.exitButton.setAutoExclusive(True)
        self.exitButton.setObjectName("exitButton")
        self.functionWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.functionWidget.setGeometry(QtCore.QRect(210, 60, 1011, 671))
        self.functionWidget.setObjectName("functionWidget")
        self.lawyerPage = QtWidgets.QWidget()
        self.lawyerPage.setObjectName("lawyerPage")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.lawyerPage)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 331, 84))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lawyerTitle = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lawyerTitle.setFont(font)
        self.lawyerTitle.setObjectName("lawyerTitle")
        self.verticalLayout_2.addWidget(self.lawyerTitle)
        self.lawyerDesc = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lawyerDesc.setFont(font)
        self.lawyerDesc.setObjectName("lawyerDesc")
        self.verticalLayout_2.addWidget(self.lawyerDesc)
        self.lawyerDisplay = QtWidgets.QTableWidget(self.lawyerPage)
        self.lawyerDisplay.setGeometry(QtCore.QRect(20, 160, 971, 501))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.lawyerDisplay.setFont(font)
        self.lawyerDisplay.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lawyerDisplay.setShowGrid(True)
        self.lawyerDisplay.setGridStyle(QtCore.Qt.SolidLine)
        self.lawyerDisplay.setWordWrap(True)
        self.lawyerDisplay.setCornerButtonEnabled(True)
        self.lawyerDisplay.setObjectName("lawyerDisplay")
        self.lawyerDisplay.setColumnCount(6)
        self.lawyerDisplay.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.lawyerDisplay.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lawyerDisplay.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lawyerDisplay.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.lawyerDisplay.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.lawyerDisplay.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.lawyerDisplay.setHorizontalHeaderItem(5, item)
        self.lawyerDisplay.horizontalHeader().setVisible(False)
        self.lawyerDisplay.horizontalHeader().setCascadingSectionResizes(False)
        self.lawyerDisplay.horizontalHeader().setDefaultSectionSize(150)
        self.lawyerDisplay.horizontalHeader().setSortIndicatorShown(True)
        self.lawyerDisplay.horizontalHeader().setStretchLastSection(True)
        self.lawyerDisplay.verticalHeader().setVisible(False)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.lawyerPage)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 110, 971, 39))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addLawyer = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.addLawyer.setFont(font)
        self.addLawyer.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 139, 0);\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    height: 35px;\n"
"    width: 100px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        self.addLawyer.setObjectName("addLawyer")
        self.horizontalLayout.addWidget(self.addLawyer)
        self.deleteLawyer = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.deleteLawyer.setFont(font)
        self.deleteLawyer.setStyleSheet("QPushButton{\n"
"    background-color: rgb(202, 0, 0);\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    height: 35px;\n"
"    width: 120px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(207, 64, 64);\n"
"}")
        self.deleteLawyer.setObjectName("deleteLawyer")
        self.horizontalLayout.addWidget(self.deleteLawyer)
        self.searchLawyer = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.searchLawyer.setFont(font)
        self.searchLawyer.setStyleSheet("QLineEdit{\n"
"    border: 1px solid grey;\n"
"    border-radius: 15px;\n"
"    height: 35px;\n"
"    \n"
"}")
        self.searchLawyer.setText("")
        self.searchLawyer.setObjectName("searchLawyer")
        self.horizontalLayout.addWidget(self.searchLawyer)
        self.editLawyer = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.editLawyer.setFont(font)
        self.editLawyer.setStyleSheet("QPushButton{\n"
"    background-color: #1d3453;\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    height: 35px;\n"
"    width: 120px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(51, 93, 148);\n"
"}")
        self.editLawyer.setObjectName("editLawyer")
        self.horizontalLayout.addWidget(self.editLawyer)
        self.functionWidget.addWidget(self.lawyerPage)
        self.clientPage = QtWidgets.QWidget()
        self.clientPage.setObjectName("clientPage")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.clientPage)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 331, 84))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.clientTitle = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.clientTitle.setFont(font)
        self.clientTitle.setObjectName("clientTitle")
        self.verticalLayout_3.addWidget(self.clientTitle)
        self.clientDesc = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.clientDesc.setFont(font)
        self.clientDesc.setObjectName("clientDesc")
        self.verticalLayout_3.addWidget(self.clientDesc)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.clientPage)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 110, 971, 39))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addClient = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.addClient.setFont(font)
        self.addClient.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 139, 0);\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    height: 35px;\n"
"    width: 100px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        self.addClient.setObjectName("addClient")
        self.horizontalLayout_2.addWidget(self.addClient)
        self.deleteClient = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.deleteClient.setFont(font)
        self.deleteClient.setStyleSheet("QPushButton{\n"
"    background-color: rgb(202, 0, 0);\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    height: 35px;\n"
"    width: 120px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(207, 64, 64);\n"
"}")
        self.deleteClient.setObjectName("deleteClient")
        self.horizontalLayout_2.addWidget(self.deleteClient)
        self.searchClient = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.searchClient.setFont(font)
        self.searchClient.setStyleSheet("QLineEdit{\n"
"    border: 1px solid grey;\n"
"    border-radius: 15px;\n"
"    height: 35px;\n"
"    \n"
"}")
        self.searchClient.setText("")
        self.searchClient.setObjectName("searchClient")
        self.horizontalLayout_2.addWidget(self.searchClient)
        self.editClient = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.editClient.setFont(font)
        self.editClient.setStyleSheet("QPushButton{\n"
"    background-color: #1d3453;\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    height: 35px;\n"
"    width: 120px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(51, 93, 148);\n"
"}")
        self.editClient.setObjectName("editClient")
        self.horizontalLayout_2.addWidget(self.editClient)
        self.clientDisplay = QtWidgets.QTableWidget(self.clientPage)
        self.clientDisplay.setGeometry(QtCore.QRect(20, 160, 971, 501))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.clientDisplay.setFont(font)
        self.clientDisplay.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clientDisplay.setShowGrid(True)
        self.clientDisplay.setGridStyle(QtCore.Qt.SolidLine)
        self.clientDisplay.setObjectName("clientDisplay")
        self.clientDisplay.setColumnCount(5)
        self.clientDisplay.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.clientDisplay.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientDisplay.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientDisplay.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientDisplay.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.clientDisplay.setHorizontalHeaderItem(4, item)
        self.clientDisplay.horizontalHeader().setVisible(False)
        self.clientDisplay.horizontalHeader().setCascadingSectionResizes(False)
        self.clientDisplay.horizontalHeader().setDefaultSectionSize(180)
        self.clientDisplay.horizontalHeader().setSortIndicatorShown(True)
        self.clientDisplay.horizontalHeader().setStretchLastSection(True)
        self.clientDisplay.verticalHeader().setVisible(False)
        self.functionWidget.addWidget(self.clientPage)
        self.casePage = QtWidgets.QWidget()
        self.casePage.setObjectName("casePage")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.casePage)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 10, 331, 84))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.caseTitle = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.caseTitle.setFont(font)
        self.caseTitle.setObjectName("caseTitle")
        self.verticalLayout_4.addWidget(self.caseTitle)
        self.caseDesc = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.caseDesc.setFont(font)
        self.caseDesc.setObjectName("caseDesc")
        self.verticalLayout_4.addWidget(self.caseDesc)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.casePage)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 110, 971, 39))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addCase = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.addCase.setFont(font)
        self.addCase.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 139, 0);\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    height: 35px;\n"
"    width: 100px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        self.addCase.setObjectName("addCase")
        self.horizontalLayout_3.addWidget(self.addCase)
        self.deleteCase = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.deleteCase.setFont(font)
        self.deleteCase.setStyleSheet("QPushButton{\n"
"    background-color: rgb(202, 0, 0);\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    height: 35px;\n"
"    width: 120px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(207, 64, 64);\n"
"}")
        self.deleteCase.setObjectName("deleteCase")
        self.horizontalLayout_3.addWidget(self.deleteCase)
        self.searchClient_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.searchClient_2.setFont(font)
        self.searchClient_2.setStyleSheet("QLineEdit{\n"
"    border: 1px solid grey;\n"
"    border-radius: 15px;\n"
"    height: 35px;\n"
"    \n"
"}")
        self.searchClient_2.setText("")
        self.searchClient_2.setObjectName("searchClient_2")
        self.horizontalLayout_3.addWidget(self.searchClient_2)
        self.editCase = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.editCase.setFont(font)
        self.editCase.setStyleSheet("QPushButton{\n"
"    background-color: #1d3453;\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    height: 35px;\n"
"    width: 120px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(51, 93, 148);\n"
"}")
        self.editCase.setObjectName("editCase")
        self.horizontalLayout_3.addWidget(self.editCase)
        self.caseDisplay = QtWidgets.QTableWidget(self.casePage)
        self.caseDisplay.setGeometry(QtCore.QRect(20, 160, 971, 491))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.caseDisplay.setFont(font)
        self.caseDisplay.setFocusPolicy(QtCore.Qt.NoFocus)
        self.caseDisplay.setShowGrid(True)
        self.caseDisplay.setGridStyle(QtCore.Qt.SolidLine)
        self.caseDisplay.setObjectName("caseDisplay")
        self.caseDisplay.setColumnCount(6)
        self.caseDisplay.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.caseDisplay.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.caseDisplay.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.caseDisplay.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.caseDisplay.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.caseDisplay.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.caseDisplay.setHorizontalHeaderItem(5, item)
        self.caseDisplay.horizontalHeader().setVisible(False)
        self.caseDisplay.horizontalHeader().setCascadingSectionResizes(False)
        self.caseDisplay.horizontalHeader().setDefaultSectionSize(160)
        self.caseDisplay.horizontalHeader().setSortIndicatorShown(True)
        self.caseDisplay.horizontalHeader().setStretchLastSection(True)
        self.caseDisplay.verticalHeader().setVisible(False)
        self.functionWidget.addWidget(self.casePage)
        self.case_lawyer_client_page = QtWidgets.QWidget()
        self.case_lawyer_client_page.setObjectName("case_lawyer_client_page")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.case_lawyer_client_page)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 10, 401, 84))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lawyer_clientTitle = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lawyer_clientTitle.setFont(font)
        self.lawyer_clientTitle.setObjectName("lawyer_clientTitle")
        self.verticalLayout_5.addWidget(self.lawyer_clientTitle)
        self.lawyer_clientDesc = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lawyer_clientDesc.setFont(font)
        self.lawyer_clientDesc.setObjectName("lawyer_clientDesc")
        self.verticalLayout_5.addWidget(self.lawyer_clientDesc)
        self.client_case_display = QtWidgets.QTableWidget(self.case_lawyer_client_page)
        self.client_case_display.setGeometry(QtCore.QRect(10, 150, 491, 471))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.client_case_display.setFont(font)
        self.client_case_display.setFocusPolicy(QtCore.Qt.NoFocus)
        self.client_case_display.setShowGrid(True)
        self.client_case_display.setGridStyle(QtCore.Qt.SolidLine)
        self.client_case_display.setObjectName("client_case_display")
        self.client_case_display.setColumnCount(2)
        self.client_case_display.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.client_case_display.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.client_case_display.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.client_case_display.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.client_case_display.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.client_case_display.setItem(0, 1, item)
        self.client_case_display.horizontalHeader().setVisible(True)
        self.client_case_display.horizontalHeader().setCascadingSectionResizes(False)
        self.client_case_display.horizontalHeader().setDefaultSectionSize(250)
        self.client_case_display.horizontalHeader().setSortIndicatorShown(True)
        self.client_case_display.horizontalHeader().setStretchLastSection(False)
        self.client_case_display.verticalHeader().setVisible(False)
        self.client_case_display.verticalHeader().setStretchLastSection(False)
        self.lawyer_case_display = QtWidgets.QTableWidget(self.case_lawyer_client_page)
        self.lawyer_case_display.setGeometry(QtCore.QRect(530, 150, 461, 471))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        self.lawyer_case_display.setFont(font)
        self.lawyer_case_display.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lawyer_case_display.setShowGrid(True)
        self.lawyer_case_display.setGridStyle(QtCore.Qt.SolidLine)
        self.lawyer_case_display.setObjectName("lawyer_case_display")
        self.lawyer_case_display.setColumnCount(3)
        self.lawyer_case_display.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.lawyer_case_display.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lawyer_case_display.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lawyer_case_display.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lawyer_case_display.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.lawyer_case_display.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lawyer_case_display.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.lawyer_case_display.setItem(0, 2, item)
        self.lawyer_case_display.horizontalHeader().setVisible(True)
        self.lawyer_case_display.horizontalHeader().setCascadingSectionResizes(False)
        self.lawyer_case_display.horizontalHeader().setDefaultSectionSize(160)
        self.lawyer_case_display.horizontalHeader().setSortIndicatorShown(True)
        self.lawyer_case_display.horizontalHeader().setStretchLastSection(True)
        self.lawyer_case_display.verticalHeader().setVisible(False)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.case_lawyer_client_page)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 100, 491, 42))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.add_clientcase_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.add_clientcase_btn.setFont(font)
        self.add_clientcase_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 139, 0);\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    height: 35px;\n"
"    width: 130px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        self.add_clientcase_btn.setObjectName("add_clientcase_btn")
        self.horizontalLayout_4.addWidget(self.add_clientcase_btn)
        self.search_client_case = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.search_client_case.setFont(font)
        self.search_client_case.setStyleSheet("QLineEdit{\n"
"    border: 1px solid grey;\n"
"    border-radius: 15px;\n"
"    height: 35px;\n"
"    \n"
"}")
        self.search_client_case.setText("")
        self.search_client_case.setObjectName("search_client_case")
        self.horizontalLayout_4.addWidget(self.search_client_case)
        self.client_case_delete = QtWidgets.QPushButton(self.case_lawyer_client_page)
        self.client_case_delete.setGeometry(QtCore.QRect(10, 630, 151, 35))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.client_case_delete.setFont(font)
        self.client_case_delete.setStyleSheet("QPushButton{\n"
"    background-color: rgb(202, 0, 0);\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    height: 35px;\n"
"    width: 120px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(207, 64, 64);\n"
"}")
        self.client_case_delete.setObjectName("client_case_delete")
        self.client_case_edit = QtWidgets.QPushButton(self.case_lawyer_client_page)
        self.client_case_edit.setGeometry(QtCore.QRect(170, 630, 151, 35))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.client_case_edit.setFont(font)
        self.client_case_edit.setStyleSheet("QPushButton{\n"
"    background-color: #1d3453;\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    height: 35px;\n"
"    width: 120px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(51, 93, 148);\n"
"}")
        self.client_case_edit.setObjectName("client_case_edit")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.case_lawyer_client_page)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(530, 100, 461, 39))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.add_lawyercase_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.add_lawyercase_btn.setFont(font)
        self.add_lawyercase_btn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 139, 0);\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    height: 35px;\n"
"    width: 140px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        self.add_lawyercase_btn.setObjectName("add_lawyercase_btn")
        self.horizontalLayout_5.addWidget(self.add_lawyercase_btn)
        self.search_lawyer_case = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(10)
        self.search_lawyer_case.setFont(font)
        self.search_lawyer_case.setStyleSheet("QLineEdit{\n"
"    border: 1px solid grey;\n"
"    border-radius: 15px;\n"
"    height: 35px;\n"
"    \n"
"}")
        self.search_lawyer_case.setText("")
        self.search_lawyer_case.setObjectName("search_lawyer_case")
        self.horizontalLayout_5.addWidget(self.search_lawyer_case)
        self.delete_lawyer_case = QtWidgets.QPushButton(self.case_lawyer_client_page)
        self.delete_lawyer_case.setGeometry(QtCore.QRect(530, 630, 161, 35))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.delete_lawyer_case.setFont(font)
        self.delete_lawyer_case.setStyleSheet("QPushButton{\n"
"    background-color: rgb(202, 0, 0);\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    height: 35px;\n"
"    width: 120px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(207, 64, 64);\n"
"}")
        self.delete_lawyer_case.setObjectName("delete_lawyer_case")
        self.edit_lawyer_case = QtWidgets.QPushButton(self.case_lawyer_client_page)
        self.edit_lawyer_case.setGeometry(QtCore.QRect(700, 630, 151, 35))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.edit_lawyer_case.setFont(font)
        self.edit_lawyer_case.setStyleSheet("QPushButton{\n"
"    background-color: #1d3453;\n"
"    color:white;\n"
"    border:none;\n"
"    border-radius: 8px;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    height: 35px;\n"
"    width: 120px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color:rgb(51, 93, 148);\n"
"}")
        self.edit_lawyer_case.setObjectName("edit_lawyer_case")
        self.functionWidget.addWidget(self.case_lawyer_client_page)
        self.titleWidget = QtWidgets.QWidget(self.centralwidget)
        self.titleWidget.setGeometry(QtCore.QRect(0, 0, 1211, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setBold(True)
        font.setWeight(75)
        self.titleWidget.setFont(font)
        self.titleWidget.setStyleSheet("#titleWidget{\n"
"background-color:#142b39;\n"
"}\n"
"#title{\n"
"color:white;\n"
"font-size:35px;\n"
"}")
        self.titleWidget.setObjectName("titleWidget")
        self.title = QtWidgets.QLabel(self.titleWidget)
        self.title.setGeometry(QtCore.QRect(60, 0, 581, 61))
        font = QtGui.QFont()
        font.setFamily("Poppins")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.functionWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lawyerButton.setText(_translate("MainWindow", "Lawyer Page"))
        self.clientButton.setText(_translate("MainWindow", "Client List"))
        self.caseButton.setText(_translate("MainWindow", "Case List"))
        self.caseButton_2.setText(_translate("MainWindow", "Lawyer/Client Cases"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.lawyerTitle.setText(_translate("MainWindow", "Lawyer Information"))
        self.lawyerDesc.setText(_translate("MainWindow", "Welcome to the lawyer information page."))
        self.lawyerDisplay.setSortingEnabled(True)
        item = self.lawyerDisplay.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Lawyer ID"))
        item = self.lawyerDisplay.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.lawyerDisplay.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.lawyerDisplay.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Position"))
        item = self.lawyerDisplay.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Specialization"))
        item = self.lawyerDisplay.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "E-Mail"))
        self.addLawyer.setText(_translate("MainWindow", " Add Lawyer"))
        self.deleteLawyer.setText(_translate("MainWindow", "Delete Lawyer"))
        self.searchLawyer.setPlaceholderText(_translate("MainWindow", "Search Lawyer Here (ID, Name, Position, Specialization, E-Mail)"))
        self.editLawyer.setText(_translate("MainWindow", "Edit Info"))
        self.clientTitle.setText(_translate("MainWindow", "Client Information"))
        self.clientDesc.setText(_translate("MainWindow", "Welcome to the client information page."))
        self.addClient.setText(_translate("MainWindow", " Add Client"))
        self.deleteClient.setText(_translate("MainWindow", "Delete Client"))
        self.searchClient.setPlaceholderText(_translate("MainWindow", "Search Client Here (ID, Name, Type, Specialization, Assigned Lawyer)"))
        self.editClient.setText(_translate("MainWindow", "Edit Client"))
        self.clientDisplay.setSortingEnabled(True)
        item = self.clientDisplay.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Client ID"))
        item = self.clientDisplay.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Client Name"))
        item = self.clientDisplay.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.clientDisplay.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Assigned Lawyer"))
        item = self.clientDisplay.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "E-Mail"))
        self.caseTitle.setText(_translate("MainWindow", "Case Information"))
        self.caseDesc.setText(_translate("MainWindow", "Welcome to the case information page."))
        self.addCase.setText(_translate("MainWindow", "Add Case"))
        self.deleteCase.setText(_translate("MainWindow", "Delete Case"))
        self.searchClient_2.setPlaceholderText(_translate("MainWindow", "Search Case Here (ID, Name, Type, Dates, Status)"))
        self.editCase.setText(_translate("MainWindow", "Edit Case"))
        self.caseDisplay.setSortingEnabled(True)
        item = self.caseDisplay.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Case ID"))
        item = self.caseDisplay.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Case Name"))
        item = self.caseDisplay.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Case Type"))
        item = self.caseDisplay.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Start Date"))
        item = self.caseDisplay.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "End Date"))
        item = self.caseDisplay.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Status"))
        self.lawyer_clientTitle.setText(_translate("MainWindow", "Cases of Lawyers and Clients"))
        self.lawyer_clientDesc.setText(_translate("MainWindow", "Welcome to the case information page."))
        self.client_case_display.setSortingEnabled(True)
        item = self.client_case_display.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.client_case_display.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Client Name"))
        item = self.client_case_display.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Case Name"))
        __sortingEnabled = self.client_case_display.isSortingEnabled()
        self.client_case_display.setSortingEnabled(False)
        item = self.client_case_display.item(0, 0)
        item.setText(_translate("MainWindow", "Morgana v Skadden"))
        item = self.client_case_display.item(0, 1)
        item.setText(_translate("MainWindow", "Civil"))
        self.client_case_display.setSortingEnabled(__sortingEnabled)
        self.lawyer_case_display.setSortingEnabled(True)
        item = self.lawyer_case_display.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.lawyer_case_display.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Assigned Lawyer"))
        item = self.lawyer_case_display.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Case Name"))
        item = self.lawyer_case_display.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Start Date"))
        __sortingEnabled = self.lawyer_case_display.isSortingEnabled()
        self.lawyer_case_display.setSortingEnabled(False)
        item = self.lawyer_case_display.item(0, 0)
        item.setText(_translate("MainWindow", "34252"))
        item = self.lawyer_case_display.item(0, 1)
        item.setText(_translate("MainWindow", "Morgana v Skadden"))
        item = self.lawyer_case_display.item(0, 2)
        item.setText(_translate("MainWindow", "Civil"))
        self.lawyer_case_display.setSortingEnabled(__sortingEnabled)
        self.add_clientcase_btn.setText(_translate("MainWindow", "Add Client Case"))
        self.search_client_case.setPlaceholderText(_translate("MainWindow", "Search Client Case Here (Client Name, Case Name)"))
        self.client_case_delete.setText(_translate("MainWindow", "Delete Client Case"))
        self.client_case_edit.setText(_translate("MainWindow", "Edit Client Case"))
        self.add_lawyercase_btn.setText(_translate("MainWindow", "Add Lawyer Case"))
        self.search_lawyer_case.setPlaceholderText(_translate("MainWindow", "Search Lawyer Case Here (Name, Date)"))
        self.delete_lawyer_case.setText(_translate("MainWindow", "Delete Lawyer Case"))
        self.edit_lawyer_case.setText(_translate("MainWindow", "Edit Lawyer Case"))
        self.title.setText(_translate("MainWindow", "Law Firm Management System"))
from static import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
